// src/app/api/generate-prd/route.ts
export const maxDuration = 90;
export const dynamic = 'force-dynamic';
import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { auth } from '@clerk/nextjs/server';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

export async function POST(request: NextRequest) {
  const startTime = Date.now();
  console.log('🚀 [Backend] PRD generation request received');
  try {
    const { userId } = await auth();
    
    if (!userId) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const body = await request.json();
    const { projectName, mindmapData, idea, features, competitors, techStack } = body;

    // Extract data from mindmapData if it's provided (handles decision tree format)
    let extractedProjectName = projectName;
    let extractedIdea = idea;
    let extractedFeatures = features;
    let extractedCompetitors = competitors;
    let extractedTechStack = techStack;

    if (mindmapData && typeof mindmapData === 'object' && Object.keys(mindmapData).length > 0) {
      // Extract from mindmapData structure (decision tree format)
      extractedProjectName = extractedProjectName || mindmapData.projectName;
      extractedIdea = extractedIdea || mindmapData.projectDescription || mindmapData.description;
      extractedFeatures = extractedFeatures || mindmapData.features;
      extractedCompetitors = extractedCompetitors || mindmapData.competitors;
      extractedTechStack = extractedTechStack || mindmapData.techStack;
      
      // Also extract other useful fields
      const targetAudience = mindmapData.targetAudience;
      const userPersona = mindmapData.userPersona;
      const monetization = mindmapData.monetization;
      
      console.log('📦 [Backend] Extracted from mindmapData:', {
        hasProjectName: !!extractedProjectName,
        hasIdea: !!extractedIdea,
        featuresCount: extractedFeatures?.length || 0,
        competitorsCount: extractedCompetitors?.length || 0,
        hasTechStack: !!extractedTechStack,
        hasTargetAudience: !!targetAudience,
        hasUserPersona: !!userPersona,
        hasMonetization: !!monetization,
      });
    }

    // Validate required inputs
    if (!extractedProjectName) {
      console.warn('⚠️ [Backend] Missing projectName');
      return NextResponse.json(
        { success: false, error: 'Project name is required' },
        { status: 400 }
      );
    }

    if (!mindmapData || (typeof mindmapData === 'object' && Object.keys(mindmapData).length === 0)) {
      console.warn('⚠️ [Backend] Missing or empty mindmapData');
      return NextResponse.json(
        { success: false, error: 'Mindmap data is required' },
        { status: 400 }
      );
    }

    // Build comprehensive prompt for PRD generation
    const prompt = `You are a senior product manager creating a comprehensive Product Requirements Document (PRD).

IMPORTANT:
- Do NOT include any references to AI models, Claude, or Anthropic
- Do NOT add metadata about how the document was generated
- Do NOT include 'Model:' or 'Generated by:' sections
- Focus only on the product requirements

PROJECT DETAILS:
- Project Name: ${extractedProjectName}
- Description: ${extractedIdea || 'No description provided'}
${extractedFeatures ? `- Key Features: ${JSON.stringify(extractedFeatures, null, 2)}` : ''}
${extractedCompetitors ? `- Competitors: ${JSON.stringify(extractedCompetitors, null, 2)}` : ''}
${extractedTechStack ? `- Tech Stack: ${JSON.stringify(extractedTechStack, null, 2)}` : ''}
${mindmapData?.targetAudience ? `- Target Audience: ${mindmapData.targetAudience}` : ''}
${mindmapData?.userPersona ? `- User Persona: ${JSON.stringify(mindmapData.userPersona, null, 2)}` : ''}
${mindmapData?.monetization ? `- Monetization Strategy: ${JSON.stringify(mindmapData.monetization, null, 2)}` : ''}

Create a detailed PRD that includes:

1. **Executive Summary**
   - Project overview
   - Vision and goals
   - Success metrics

2. **Problem Statement**
   - User pain points
   - Market opportunity
   - Why this solution is needed

3. **Target Users**
   - User personas (3-5 detailed personas)
   - User journey maps
   - Use cases

4. **Feature Requirements**
   - Core features (detailed, with user stories)
   - Nice-to-have features
   - Future roadmap ideas
   - Acceptance criteria for each feature

5. **Technical Requirements**
   - Architecture overview
   - Technology recommendations
   - Scalability considerations
   - Security requirements
   - Integration requirements

6. **User Experience**
   - Key user flows
   - Wireframe descriptions
   - Interaction patterns
   - Accessibility requirements

7. **Business Model**
   - Monetization strategy
   - Pricing model
   - Revenue projections
   - Go-to-market strategy

8. **Competitive Analysis**
   - Direct competitors
   - Indirect competitors
   - Competitive advantages
   - Market positioning

9. **Success Metrics (KPIs)**
   - User acquisition metrics
   - Engagement metrics
   - Revenue metrics
   - Technical metrics

10. **Implementation Roadmap**
    - MVP scope
    - Phase 1 (Months 1-3)
    - Phase 2 (Months 4-6)
    - Phase 3 (Months 7-12)

11. **Risk Assessment**
    - Technical risks
    - Market risks
    - Mitigation strategies

12. **Resources & Timeline**
    - Team requirements
    - Budget estimates
    - Timeline estimates

Return the PRD in a structured JSON format with clear sections and subsections. Make it professional, comprehensive, and actionable.`;

    console.log('📦 [Backend] Request validated:', {
      projectName: extractedProjectName,
      idea: extractedIdea?.substring(0, 100) + '...',
      featuresCount: extractedFeatures?.length || 0,
      competitorsCount: extractedCompetitors?.length || 0,
      hasTechStack: !!extractedTechStack,
      mindmapSize: JSON.stringify(mindmapData).length,
    });

    console.log('🤖 [Backend] Calling Anthropic API...');
    const message = await anthropic.messages.create({
      model: 'claude-sonnet-4-5-20250929',
      max_tokens: 4096,
      temperature: 0.7,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    });

    const duration = Date.now() - startTime;
    console.log(`✅ [Backend] Anthropic responded in ${duration}ms`);
    // @ts-ignore usage may be present depending on SDK version
    if ((message as any)?.usage) {
      // @ts-ignore
      console.log('📊 [Backend] Token usage:', (message as any).usage);
    }

    const responseText = message.content[0].type === 'text' 
      ? message.content[0].text 
      : '';

    // Clean any accidental model references
    const cleanedPrdContent = responseText
      .replace(/#{1,6}\s*Model:?\s*[^\n]*/gi, '')
      .replace(/#{1,6}\s*Generated by:?\s*[^\n]*/gi, '')
      .replace(/Model:\s*claude[^\n]*/gi, '')
      .replace(/Generated by Claude[^\n]*/gi, '')
      .replace(/Anthropic's Claude[^\n]*/gi, '')
      .split('\n')
      .filter((line) => !line.toLowerCase().includes('claude-sonnet'))
      .join('\n')
      .trim();

    return NextResponse.json({
      success: true,
      data: {
        rawText: cleanedPrdContent,
        metadata: {
          projectName: extractedProjectName,
          generatedAt: new Date().toISOString(),
          model: 'redacted',
          // @ts-ignore usage may be present
          tokensUsed: (message as any)?.usage,
          processingTime: duration,
        },
      },
    });

  } catch (error: any) {
    const duration = Date.now() - startTime;
    console.error('❌ [Backend] PRD generation failed:', {
      error: error?.message,
      duration,
      stack: error?.stack,
      status: error?.status,
      code: error?.code,
    });

    if (error?.status === 401) {
      return NextResponse.json(
        { success: false, error: 'API authentication failed' },
        { status: 500 }
      );
    }

    if (error?.status === 429) {
      return NextResponse.json(
        { success: false, error: 'Rate limit exceeded. Please try again later.' },
        { status: 429 }
      );
    }

    return NextResponse.json(
      { 
        success: false, 
        error: error?.message || 'Failed to generate PRD',
        code: error?.code || 'INTERNAL_ERROR',
      },
      { status: 500 }
    );
  }
}

// Removed JSON parsing helper; we return raw text to avoid double-encoding

