// FILE PATH: src/components/DemoMindmapDisplay.tsx
// Pre-built demo mindmap with explanatory tooltips

'use client';

import { useState } from 'react';
import { Sparkles, FileText, Code, Users, TrendingUp } from 'lucide-react';
import { SpaceBackground } from '@/components/ui/space-background';

const DEMO_PROJECT = {
  projectName: "FitConnect - Social Fitness App",
  projectDescription: "A mobile fitness application that combines workout tracking with social features, allowing users to share progress, compete with friends, and discover new exercises.",
  features: [
    {
      id: '1',
      title: 'Workout Tracking',
      description: 'Log exercises, sets, reps, and weights with an intuitive interface',
      priority: 'high' as const,
    },
    {
      id: '2',
      title: 'Social Feed',
      description: 'Share workout achievements and progress photos with friends',
      priority: 'high' as const,
    },
    {
      id: '3',
      title: 'Progress Analytics',
      description: 'Visual charts showing strength gains, consistency, and goal tracking',
      priority: 'high' as const,
    },
    {
      id: '4',
      title: 'Exercise Library',
      description: 'Comprehensive database of exercises with video demonstrations',
      priority: 'medium' as const,
    },
    {
      id: '5',
      title: 'Custom Workout Plans',
      description: 'Create and share personalized workout routines',
      priority: 'medium' as const,
    },
    {
      id: '6',
      title: 'Friend Challenges',
      description: 'Compete with friends in weekly fitness challenges',
      priority: 'low' as const,
    },
  ],
  targetAudience: "Fitness enthusiasts aged 18-45 who want to stay motivated through social accountability",
  techStack: {
    frontend: "React Native",
    backend: "Node.js/Express",
    database: "PostgreSQL",
    auth: "Firebase Auth",
    payments: "Stripe",
    hosting: "AWS",
  },
  monetization: {
    model: 'freemium' as const,
    pricing: "$9.99/month for Pro features",
    freeTier: "Basic workout tracking and limited social features",
    paidTier: "Unlimited workouts, advanced analytics, custom plans, ad-free",
  },
};

type TooltipStep = 'mindmap' | 'features' | 'details' | 'prd' | null;

export default function DemoMindmapDisplay() {
  const [activeTooltip, setActiveTooltip] = useState<TooltipStep>('mindmap');
  const [selectedFeature, setSelectedFeature] = useState<string | null>(null);

  const nextTooltip = () => {
    if (activeTooltip === 'mindmap') setActiveTooltip('features');
    else if (activeTooltip === 'features') setActiveTooltip('details');
    else if (activeTooltip === 'details') setActiveTooltip('prd');
    else if (activeTooltip === 'prd') setActiveTooltip(null);
  };

  return (
    <SpaceBackground variant="default">
      <div className="relative">
        {/* Tooltip Overlay */}
        {activeTooltip && (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-40 flex items-center justify-center p-6">
            <div className="bg-gray-800 border-2 border-purple-500 rounded-2xl p-8 max-w-lg shadow-2xl">
            {activeTooltip === 'mindmap' && (
              <>
                <div className="flex items-center gap-3 mb-4">
                  <Sparkles className="w-8 h-8 text-purple-400" />
                  <h3 className="text-2xl font-bold text-white">Your AI-Generated Mindmap</h3>
                </div>
                <p className="text-gray-300 text-lg mb-6">
                  This is what CodeLaunch creates from a simple app description. Each bubble represents a key feature of your app.
                </p>
              </>
            )}

            {activeTooltip === 'features' && (
              <>
                <div className="flex items-center gap-3 mb-4">
                  <Code className="w-8 h-8 text-purple-400" />
                  <h3 className="text-2xl font-bold text-white">Click Any Feature</h3>
                </div>
                <p className="text-gray-300 text-lg mb-6">
                  Click on any feature bubble to see detailed planning information, including user stories, technical specs, and implementation details.
                </p>
              </>
            )}

            {activeTooltip === 'details' && (
              <>
                <div className="flex items-center gap-3 mb-4">
                  <Users className="w-8 h-8 text-purple-400" />
                  <h3 className="text-2xl font-bold text-white">Complete Project Details</h3>
                </div>
                <p className="text-gray-300 text-lg mb-6">
                  See target audience, tech stack recommendations, competitors, and monetization strategies - all generated by AI.
                </p>
              </>
            )}

            {activeTooltip === 'prd' && (
              <>
                <div className="flex items-center gap-3 mb-4">
                  <FileText className="w-8 h-8 text-purple-400" />
                  <h3 className="text-2xl font-bold text-white">Generate PRDs</h3>
                </div>
                <p className="text-gray-300 text-lg mb-6">
                  Generate professional Product Requirement Documents for any feature - ready to hand off to developers.
                </p>
              </>
            )}

            <button
              onClick={nextTooltip}
              className="w-full px-6 py-3 bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white font-semibold rounded-xl transition-all"
            >
              {activeTooltip === 'prd' ? 'Got It!' : 'Next'}
            </button>
          </div>
        </div>
      )}

        {/* Demo Mindmap Display */}
        <div className="bg-gray-900/40 backdrop-blur-sm border border-purple-500/20 rounded-2xl p-8 relative z-10">
        {/* Project Header */}
        <div className="mb-8 text-center">
          <h2 className="text-3xl font-bold text-white mb-2">
            {DEMO_PROJECT.projectName}
          </h2>
          <p className="text-gray-400">
            {DEMO_PROJECT.projectDescription}
          </p>
        </div>

        {/* Feature Bubbles in Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-8">
          {DEMO_PROJECT.features.map((feature) => (
            <button
              key={feature.id}
              onClick={() => setSelectedFeature(selectedFeature === feature.id ? null : feature.id)}
              className={`p-6 rounded-xl border-2 transition-all transform hover:scale-105 ${
                selectedFeature === feature.id
                  ? 'bg-purple-500/20 border-purple-400 shadow-lg shadow-purple-500/50'
                  : 'bg-gray-700/30 border-gray-600 hover:border-purple-500/50'
              }`}
            >
              <div className="flex items-start justify-between mb-2">
                <h3 className="text-lg font-semibold text-white text-left">
                  {feature.title}
                </h3>
                <span className={`text-xs px-2 py-1 rounded-full ${
                  feature.priority === 'high' ? 'bg-red-500/20 text-red-300' :
                  feature.priority === 'medium' ? 'bg-yellow-500/20 text-yellow-300' :
                  'bg-green-500/20 text-green-300'
                }`}>
                  {feature.priority}
                </span>
              </div>
              <p className="text-sm text-gray-400 text-left">
                {feature.description}
              </p>

              {selectedFeature === feature.id && (
                <div className="mt-4 pt-4 border-t border-gray-600">
                  <div className="text-left space-y-2">
                    <div className="flex items-center gap-2 text-sm text-purple-300">
                      <FileText className="w-4 h-4" />
                      <span>User stories generated</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm text-purple-300">
                      <Code className="w-4 h-4" />
                      <span>Technical specs ready</span>
                    </div>
                    <div className="flex items-center gap-2 text-sm text-purple-300">
                      <TrendingUp className="w-4 h-4" />
                      <span>Implementation details available</span>
                    </div>
                  </div>
                </div>
              )}
            </button>
          ))}
        </div>

        {/* Project Details */}
        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-gray-700/30 rounded-xl p-6 border border-gray-600">
            <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
              <Users className="w-5 h-5 text-purple-400" />
              Target Audience
            </h3>
            <p className="text-gray-300">{DEMO_PROJECT.targetAudience}</p>
          </div>

          <div className="bg-gray-700/30 rounded-xl p-6 border border-gray-600">
            <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-purple-400" />
              Monetization
            </h3>
            <p className="text-gray-300 mb-2">
              <strong>Model:</strong> {DEMO_PROJECT.monetization.model}
            </p>
            <p className="text-gray-300">{DEMO_PROJECT.monetization.pricing}</p>
          </div>
        </div>

        <div className="mt-6 p-4 bg-purple-500/10 border border-purple-500/30 rounded-lg text-center">
          <p className="text-purple-200">
            ✨ <strong>This entire project plan was generated in seconds</strong> from just a simple description!
          </p>
        </div>
      </div>
    </div>
    </SpaceBackground>
  );
}
